# Generated by Django 3.2.6 on 2021-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210911_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=80)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Lastname', models.CharField(default='', max_length=50)),
                ('City', models.CharField(default='', max_length=20)),
                ('phonenumber', models.IntegerField(default=0)),
                ('Query', models.CharField(max_length=400)),
            ],
        ),
    ]
